{% set name = "pywinpty" %}
{% set version = "0.5.1" %}
{% set hash = "03df08a483c7d2e51ddcd01abca4c338166725b69dfd27d7400d6b7b856bf3c1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/spyder-ide/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  skip: True  # [not win]

requirements:
  # use m2w64 toolchain for building
  host:
    - python
    - setuptools
    - cython
    - winpty
    - m2w64-toolchain
    - libpython
    - backports.shutil_which  # [py2k]
  run:
    - python
    - winpty
    - m2w64-gcc-libs
    - backports.shutil_which  # [py2k]

test:
  imports:
    - winpty

about:
  home: https://github.com/spyder-ide/pywinpty
  license: MIT
  summary: 'Python bindings for the winpty library'
  description: |
    Python bindings for the winpty pseudo terminal library.
    It allows to create and communicate with Windows processes that print outputs
     and recieve inputs via console input and output pipes.
  doc_url: https://github.com/spyder-ide/pywinpty
  dev_url: https://github.com/spyder-ide/pywinpty

extra:
  recipe-maintainers:
    - blink1073
    - ccordoba12
    - andfoy
    - goanpeca
    - jjhelmus
