{% set name = "pywinpty" %}
{% set version = "0.5.2" %}
{% set hash = "7049f68189e19ffbef069a2a3ae6ed011ecc3c55b3750685839283429346f19e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  skip: True  # [not win]

requirements:
  build:
    - cython
    - python
    - setuptools
    - winpty
    - backports.shutil_which  # [py2k]
    # use the m2w64 toolchain for all builds
    - m2w64-toolchain
    - libpython
  run:
    - backports.shutil_which  # [py2k]
    - setuptools  # [py2k]
    - python
    - winpty
    - m2w64-gcc-libs

test:
  imports:
    - winpty

about:
  home: https://github.com/spyder-ide/pywinpty
  license: MIT
  summary: 'Python bindings for the winpty library'
  description: |
    Python bindings for the winpty pseudo terminal library.
    It allows to create and communicate with Windows processes that print outputs
     and recieve inputs via console input and output pipes.
  doc_url: https://github.com/spyder-ide/pywinpty
  dev_url: https://github.com/spyder-ide/pywinpty

extra:
  recipe-maintainers:
    - blink1073
    - ccordoba12
    - andfoy
    - goanpeca
    - jjhelmus
