{% set version = "1.1.3" %}

package:
  name: pywinpty
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pywinpty/pywinpty-{{ version }}.tar.gz
  sha256: 3a1d57b338390333812a5eed31c93c7d8ba82b131078063703e731946d90c9f2

build:
  number: 0
  skip: True  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clang
    - llvm
    - rust
    - llvmdev
    - llvm-tools
    - libclang
    - maturin
    - toml
    - pip
    - winpty
  host:
    - python >=3.6
    - pip
    - winpty
    - backports.shutil_which  # [py2k]
    # use the m2w64 toolchain for all builds
    - m2w64-toolchain
    - libpython
  run:
    - backports.shutil_which  # [py2k]
    - python >=3.6
    - winpty
    - m2w64-gcc-libs
    # ran into an overlinking error on win32. not sure if it was an issue with exports in m2w64-gcc-libs or this?
    - m2w64-gcc-libs-core     # [win32]

test:
  imports:
    # It hangs in Python 2
    - winpty  # [not py2k]

about:
  home: https://github.com/spyder-ide/pywinpty
  license: MIT
  license_file: LICENSE.txt
  summary: 'Python bindings for the winpty library'
  description: |
    Python bindings for the winpty pseudo terminal library.
    It allows to create and communicate with Windows processes that print outputs
     and recieve inputs via console input and output pipes.
  doc_url: https://github.com/spyder-ide/pywinpty
  dev_url: https://github.com/spyder-ide/pywinpty

extra:
  recipe-maintainers:
    - blink1073
    - ccordoba12
    - andfoy
    - goanpeca
    - jjhelmus
    - ocefpaf
